In [ ]:
# Python for Data Analytics project 1

In [2]:
import pandas as pd
import numpy as np

In [3]:
Student = {'name':['Safwana','Salman','Tayo','Olu','Sofiyyah','Iwa','Lewa','Ope','Kunle','Bilal'],
           'relationship':['Single','Married','Married','Single','Married','Single','Married','Single','Single','Single'],
           'Age':[15, 23, 39, 54, 27, 25, 27, 28, 29, 30,],
           'Department':['English','Maths','Biology','Maths','Biology','English','Maths','Biology','Maths','Biology']
          }
Studentser=pd.DataFrame(Student)
Studentser


name relationship  Age Department
0   Safwana       Single   15    English
1    Salman      Married   23      Maths
2      Tayo      Married   39    Biology
3       Olu       Single   54      Maths
4  Sofiyyah      Married   27    Biology
5       Iwa       Single   25    English
6      Lewa      Married   27      Maths
7       Ope       Single   28    Biology
8     Kunle       Single   29      Maths
9     Bilal       Single   30    Biology

In [38]:
import pandas as pd
import numpy as np
Student = {'name':['Safwana','Salman','Tayo','Olu','Sofiyyah','Iwa','Lewa','Ope','Kunle','Bilal'],
           'relationship':['Single','Married','Married','Single','Married','Single','Married','Single','Single','Single'],
           'Age':[15, 23, 39, 54, 27, 25, 27, 28, 29, 30,],
           'Department':['English','Maths','Biology','Maths','Biology','English','Maths','Biology','Maths','Biology']
          }
Studentser=pd.DataFrame(Student)
Studentser



#Studentser['CGPA'] = [3.5, 4.0, 4.2, 3.8, 2.6, 2.9, 3.0, 3.9, 4.5, 4.6 ]
#Studentser


name relationship  Age Department
0   Safwana       Single   15    English
1    Salman      Married   23      Maths
2      Tayo      Married   39    Biology
3       Olu       Single   54      Maths
4  Sofiyyah      Married   27    Biology
5       Iwa       Single   25    English
6      Lewa      Married   27      Maths
7       Ope       Single   28    Biology
8     Kunle       Single   29      Maths
9     Bilal       Single   30    Biology

In [39]:
Studentser['CGPA'] = [3.5, 4.0, 4.2, 3.8, 2.6, 2.9, 3.0, 3.9, 4.5, 4.6 ]
Studentser

name relationship  Age Department  CGPA
0   Safwana       Single   15    English   3.5
1    Salman      Married   23      Maths   4.0
2      Tayo      Married   39    Biology   4.2
3       Olu       Single   54      Maths   3.8
4  Sofiyyah      Married   27    Biology   2.6
5       Iwa       Single   25    English   2.9
6      Lewa      Married   27      Maths   3.0
7       Ope       Single   28    Biology   3.9
8     Kunle       Single   29      Maths   4.5
9     Bilal       Single   30    Biology   4.6

In [40]:
Studentser.pop('relationship')

0     Single
1    Married
2    Married
3     Single
4    Married
5     Single
6    Married
7     Single
8     Single
9     Single
Name: relationship, dtype: object

In [1]:
import pandas as pd
import numpy as np

In [2]:
import datetime as dt

In [3]:
Name = ['Safawana','Salman' ,'Tayo' ,'Olu', 'Sofiyyah','Iwa', 'Lewa', 'Ope', 'Kunle', 'Bilal']
Age = [15,23,39,54,27,25,27,28,29,30]
Department = ['English', 'Maths', 'Biology', 'Maths', 'Biology', 'English', 'Maths', 'Biology', 'Maths','Biology']
Admission_date = ['2017-05-14 01:30','2016-08-17 12:45', '2021-06-22 12:40', '2020-04-19 02:50', '2021-03-23 02:30' , '2016-06-27 03:40', '2015-08-28 01:25' , '2019-07-23 02:15', '2019-09-27 03:20', '2020-09-12 01:29']
Gender = ['Female', 'Male', 'Male', 'Male','Female','Female','Female', 'Male', 'Male', 'Male']
Student = pd.DataFrame({'Name': Name , 'Age':Age, 'Department':Department , 'Admission_date':Admission_date, 'Gender':Gender})
Student

Name  Age Department    Admission_date  Gender
0  Safawana   15    English  2017-05-14 01:30  Female
1    Salman   23      Maths  2016-08-17 12:45    Male
2      Tayo   39    Biology  2021-06-22 12:40    Male
3       Olu   54      Maths  2020-04-19 02:50    Male
4  Sofiyyah   27    Biology  2021-03-23 02:30  Female
5       Iwa   25    English  2016-06-27 03:40  Female
6      Lewa   27      Maths  2015-08-28 01:25  Female
7       Ope   28    Biology  2019-07-23 02:15    Male
8     Kunle   29      Maths  2019-09-27 03:20    Male
9     Bilal   30    Biology  2020-09-12 01:29    Male

In [7]:
Student['Admission_date'] = pd.to_datetime(Student['Admission_date'])

In [8]:
Student['year'] = Student['Admission_date'].dt.year
Student

Name  Age Department      Admission_date  Gender  year
0  Safawana   15    English 2017-05-14 01:30:00  Female  2017
1    Salman   23      Maths 2016-08-17 12:45:00    Male  2016
2      Tayo   39    Biology 2021-06-22 12:40:00    Male  2021
3       Olu   54      Maths 2020-04-19 02:50:00    Male  2020
4  Sofiyyah   27    Biology 2021-03-23 02:30:00  Female  2021
5       Iwa   25    English 2016-06-27 03:40:00  Female  2016
6      Lewa   27      Maths 2015-08-28 01:25:00  Female  2015
7       Ope   28    Biology 2019-07-23 02:15:00    Male  2019
8     Kunle   29      Maths 2019-09-27 03:20:00    Male  2019
9     Bilal   30    Biology 2020-09-12 01:29:00    Male  2020

In [9]:
Student['month'] = Student ['Admission_date'].dt.month
Student

Name  Age Department      Admission_date  Gender  year  month
0  Safawana   15    English 2017-05-14 01:30:00  Female  2017      5
1    Salman   23      Maths 2016-08-17 12:45:00    Male  2016      8
2      Tayo   39    Biology 2021-06-22 12:40:00    Male  2021      6
3       Olu   54      Maths 2020-04-19 02:50:00    Male  2020      4
4  Sofiyyah   27    Biology 2021-03-23 02:30:00  Female  2021      3
5       Iwa   25    English 2016-06-27 03:40:00  Female  2016      6
6      Lewa   27      Maths 2015-08-28 01:25:00  Female  2015      8
7       Ope   28    Biology 2019-07-23 02:15:00    Male  2019      7
8     Kunle   29      Maths 2019-09-27 03:20:00    Male  2019      9
9     Bilal   30    Biology 2020-09-12 01:29:00    Male  2020      9

In [10]:
Student['day'] = Student['Admission_date'].dt.day
Student

Name  Age Department      Admission_date  Gender  year  month  day
0  Safawana   15    English 2017-05-14 01:30:00  Female  2017      5   14
1    Salman   23      Maths 2016-08-17 12:45:00    Male  2016      8   17
2      Tayo   39    Biology 2021-06-22 12:40:00    Male  2021      6   22
3       Olu   54      Maths 2020-04-19 02:50:00    Male  2020      4   19
4  Sofiyyah   27    Biology 2021-03-23 02:30:00  Female  2021      3   23
5       Iwa   25    English 2016-06-27 03:40:00  Female  2016      6   27
6      Lewa   27      Maths 2015-08-28 01:25:00  Female  2015      8   28
7       Ope   28    Biology 2019-07-23 02:15:00    Male  2019      7   23
8     Kunle   29      Maths 2019-09-27 03:20:00    Male  2019      9   27
9     Bilal   30    Biology 2020-09-12 01:29:00    Male  2020      9   12

In [11]:
Student.dtypes

Name                      object
Age                        int64
Department                object
Admission_date    datetime64[ns]
Gender                    object
year                       int64
month                      int64
day                        int64
dtype: object

In [12]:
Student.isna().sum()

Name              0
Age               0
Department        0
Admission_date    0
Gender            0
year              0
month             0
day               0
dtype: int64

In [13]:
Student.isna().sum()*100

Name              0
Age               0
Department        0
Admission_date    0
Gender            0
year              0
month             0
day               0
dtype: int64

In [14]:
Student.Name.unique()

array(['Safawana', 'Salman', 'Tayo', 'Olu', 'Sofiyyah', 'Iwa', 'Lewa',
       'Ope', 'Kunle', 'Bilal'], dtype=object)

In [15]:
Student.Age.unique()

array([15, 23, 39, 54, 27, 25, 28, 29, 30], dtype=int64)

In [16]:
Student.Department.unique()

array(['English', 'Maths', 'Biology'], dtype=object)

In [18]:
Student.Admission_date.unique()

array(['2017-05-14T01:30:00.000000000', '2016-08-17T12:45:00.000000000',
       '2021-06-22T12:40:00.000000000', '2020-04-19T02:50:00.000000000',
       '2021-03-23T02:30:00.000000000', '2016-06-27T03:40:00.000000000',
       '2015-08-28T01:25:00.000000000', '2019-07-23T02:15:00.000000000',
       '2019-09-27T03:20:00.000000000', '2020-09-12T01:29:00.000000000'],
      dtype='datetime64[ns]')

In [19]:
Student.Gender.unique()

array(['Female', 'Male'], dtype=object)

In [20]:
Student.year.unique()

array([2017, 2016, 2021, 2020, 2015, 2019], dtype=int64)

In [21]:
Student.month.unique()

array([5, 8, 6, 4, 3, 7, 9], dtype=int64)

In [22]:
Student.day.unique()

array([14, 17, 22, 19, 23, 27, 28, 12], dtype=int64)

In [23]:
Student.Name.nunique()

10

In [24]:
Student.Age.nunique()

9

In [25]:
Student.Department.nunique()

3

In [26]:
Student.Admission_date.nunique()

10

In [27]:
Student.year.nunique

<bound method IndexOpsMixin.nunique of 0    2017
1    2016
2    2021
3    2020
4    2021
5    2016
6    2015
7    2019
8    2019
9    2020
Name: year, dtype: int64>

In [28]:
Student.month.nunique()

7

In [29]:
Student.day.nunique()

8

In [30]:
Student.Name.value_counts()

Safawana    1
Salman      1
Tayo        1
Olu         1
Sofiyyah    1
Iwa         1
Lewa        1
Ope         1
Kunle       1
Bilal       1
Name: Name, dtype: int64

In [31]:
Student.Age.value_counts()

27    2
15    1
23    1
39    1
54    1
25    1
28    1
29    1
30    1
Name: Age, dtype: int64

In [32]:
Student.Department.value_counts()

Maths      4
Biology    4
English    2
Name: Department, dtype: int64

In [33]:
Student.Admission_date.value_counts()

2017-05-14 01:30:00    1
2016-08-17 12:45:00    1
2021-06-22 12:40:00    1
2020-04-19 02:50:00    1
2021-03-23 02:30:00    1
2016-06-27 03:40:00    1
2015-08-28 01:25:00    1
2019-07-23 02:15:00    1
2019-09-27 03:20:00    1
2020-09-12 01:29:00    1
Name: Admission_date, dtype: int64

In [34]:
Student.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype         
---  ------          --------------  -----         
 0   Name            10 non-null     object        
 1   Age             10 non-null     int64         
 2   Department      10 non-null     object        
 3   Admission_date  10 non-null     datetime64[ns]
 4   Gender          10 non-null     object        
 5   year            10 non-null     int64         
 6   month           10 non-null     int64         
 7   day             10 non-null     int64         
dtypes: datetime64[ns](1), int64(4), object(3)
memory usage: 768.0+ bytes


In [35]:
Student.describe()

Age         year      month        day
count  10.000000    10.000000  10.000000  10.000000
mean   29.700000  2018.400000   6.500000  21.200000
std    10.424863     2.221111   2.068279   5.573748
min    15.000000  2015.000000   3.000000  12.000000
25%    25.500000  2016.250000   5.250000  17.500000
50%    27.500000  2019.000000   6.500000  22.500000
75%    29.750000  2020.000000   8.000000  26.000000
max    54.000000  2021.000000   9.000000  28.000000

In [37]:
Student.shape

(10, 8)

In [41]:
Studentser['CGPA'].min()

2.6

In [42]:
Studentser['CGPA'].max()

4.6

In [43]:
Studentser['CGPA'].mean()

3.7

In [44]:
Studentser['CGPA'].sum()

37.0

In [5]:
Gender = Student.groupby('Gender')

In [9]:
Student.to_csv('Student.csv', index = False)
pd.read_csv('Student.csv')

Name  Age Department    Admission_date  Gender
0  Safawana   15    English  2017-05-14 01:30  Female
1    Salman   23      Maths  2016-08-17 12:45    Male
2      Tayo   39    Biology  2021-06-22 12:40    Male
3       Olu   54      Maths  2020-04-19 02:50    Male
4  Sofiyyah   27    Biology  2021-03-23 02:30  Female
5       Iwa   25    English  2016-06-27 03:40  Female
6      Lewa   27      Maths  2015-08-28 01:25  Female
7       Ope   28    Biology  2019-07-23 02:15    Male
8     Kunle   29      Maths  2019-09-27 03:20    Male
9     Bilal   30    Biology  2020-09-12 01:29    Male